import Head from "next/head";
import { Inter } from "next/font/google";
import AboutSection from "@/sections/about";
import BannerSection from "@/sections/banner";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Dhara kachhadiya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Varela+Round&family=Caprasimo&display=swap" rel="stylesheet"></link>
      </Head>
      <main>
        <Header />
        <BannerSection />
        <AboutSection />
      </main>
    </>
  );
}
